USE Redes;

DROP TABLE IF EXISTS Venta;
DROP TABLE IF EXISTS Libro;
DROP TABLE IF EXISTS Vendedor;

CREATE TABLE Libro (
	Id_Libro 	INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nombre		VARCHAR(100) NOT NULL,
    Cantidad	INT NOT NULL,
    Precio		DECIMAL(8,2) NOT NULL,
    Autor		VARCHAR(100) NOT NULL,
    Fecha		DATE NOT NULL,
    Genero		VARCHAR(100) NOT NULL
);

CREATE TABLE Vendedor (
	Id_Vendedor	INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DPI			BIGINT NOT NULL,
    Nombre		VARCHAR(100) NOT NULL,
    Apellido	VARCHAR(100) NOT NULL,
    Direccion 	VARCHAR(100) NOT NULL,
    Telefono 	VARCHAR(50) NOT NULL
);

CREATE TABLE Venta (
	Id_Venta	INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Fecha		DATE NOT NULL,
    Cantidad 	INT NOT NULL,
    Total		DECIMAL(8,2) NOT NULL,
    ID_LIBRO	INT NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    CONSTRAINT FK_VENTA_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES Libro(Id_Libro),
    CONSTRAINT FK_VENTA_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES Vendedor(Id_Vendedor)
);